// src/components/desktop/section/CategoryList.jsx
import React from 'react';

export default function CategoryList() {
    return (
        <section className="list-cats">
            <a href="" className="item-cat">
                <div className="ico">
                    <img src="/images/icons/slot-game-icon.svg" alt="" />
                </div>
                <div className="name">Slot Games</div>
            </a>
            <a href="" className="item-cat">
                <div className="ico">
                    <img src="/images/icons/board-game-ico.svg" alt="" />
                </div>
                <div className="name">Board Games</div>
            </a>
            <a href="" className="item-cat">
                <div className="ico">
                    <img src="/images/icons/card-game-ico.svg" alt="" />
                </div>
                <div className="name">Card Games</div>
            </a>
        </section>
    );
}

// components/sections/CategoryList.vue
<template>
  <section class="list-cats">
    <a href="" class="item-cat">
      <div class="ico">
        <img src="/images/icons/slot-game-icon.svg" alt="" />
      </div>
      <div class="name">Slot Games</div>
    </a>
    <a href="" class="item-cat">
      <div class="ico">
        <img src="/images/icons/board-game-ico.svg" alt="" />
      </div>
      <div class="name">Board Games</div>
    </a>
    <a href="" class="item-cat">
      <div class="ico">
        <img src="/images/icons/card-game-ico.svg" alt="" />
      </div>
      <div class="name">Card Games</div>
    </a>
  </section>
</template>
